language: node_js
node_js:
- '6'
before_script:
- npm install -g gulp
script: gulp
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: pojWn13XmmWuI0jS6Q4++mV9S+YrCmKodFnR4XOMVrGuRbFL70235NfYF1iptS6XczgKRnAdpbwapYaI8wDwr+FdT+d4yO30oZbK4Pc4xF/jFI4cRseOr0FmCwwbq9JvtDRxsL1smqMRmXTPrvzKyDuciP+M40+Yk60yoUpg4i9az1ew1AMiugiaCNDUp8qni4RHYhhdjtpVmS73sv1u8yPZ/SV8K8xIoyQ1gZXXz9aqnnYj/oli+q1rmnmbvcow9qVjcSHxsmOWTOtRjUQcfk06CTdOwcjBiw65c8FYQ0/jhjHLQPuuTKy58hOUBXyfqDmb+XMT80+b2vUcvUCsj1HeHcBYrkP91oEhp4tKxeyozTeedat5Lqyx6GmnOI+jjv3gG1MfvPZaMqzQ95QxBLlSDcOeHO1sr8BQ0p4+jQsYxuUWOkQiKs1jNjz3iD26YxHwugFU32+nOzXlzQ4V6kl6scrOT/aAR9gcEZKX3n99XQyvDZBgNO6JpPS1Ln7WY9BJ6h8HXwt3Pylscy0iEOlaT0EHZUHCqklxcAQLZgorNXa0Sc4K8CQwjxP9zXrHAHgebSZEak7dJpDhEPqX59Haxbm47v6LDB2rkl07Nn4KQctP+wSzlqFyl+1i0n+Rx16zjwL/SDpYxyH0+pmgbfxVj+oNXLjC9jpoJsPICLg=
  app: cse112-node-tutorial
  on:
    repo: sujithvm/cse112-node-tutorial
